### ISSUE TITLE
Add Enchanting Table Book Entity

### ISSUE THREAD

**Issue by LizzyFleckenstein03** [22i/minecraft-voxel-blender-models#6]
I'm currently doing enchanting for MineClone2 and it would be so cool if I could add this to the mod.

**Comment by LizzyFleckenstein03** [comment]
So will you add it?

**Comment by 22i** [comment]
yep

**Comment by 22i** [comment]
its added to the objects folder - now enchant it into mineclone2

**Comment by LizzyFleckenstein03** [comment]
Done.
https://github.com/EliasFleckenstein03/mcl_enchanting in case you want to have a look at it.
(https://elidragon.com/enchanting_ressources.zip) for better textures
